import {clientBase} from "./clientBase";

//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.15.10.0 (NJsonSchema v10.6.10.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

export class Client extends clientBase {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        super();
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
    }

    /**
     * Gets the list of gadgets
     * @return Success
     */
    async gadgetsGET(): Promise<GadgetListVm> {
        let url_ = this.baseUrl + "/api/gadgets";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        const transformedOptions_ = await this.transformOptions(options_);
        const _response = await this.http.fetch(url_, transformedOptions_);
        console.log(_response);
        return await this.processGadgetsGET(_response);
    }

    protected async processGadgetsGET(response: Response): Promise<GadgetListVm> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            const _responseText = await response.text();
        let result200: any = null;
        result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as GadgetListVm;
        return result200;
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            let result401: any = null;
            result401 = _responseText === "" 
            ? null 
            : JSON.parse(_responseText, this.jsonParseReviver) as ProblemDetails;
            return throwException("If user is unauthorized", status, _responseText, _headers, result401);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<GadgetListVm>(null as any);
    }

    /**
     * Creates the gadget
     * @param body (optional) CreateGadgetDto object
     * @return Success
     */
    async gadgetsPOST(body: CreateGadgetDto | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/gadgets";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json-patch+json",
            }
        };

        const transformedOptions_ = await this.transformOptions(options_);
        console.log(transformedOptions_);
        const _response = await this.http.fetch(url_, transformedOptions_);
        console.log(_response);
        return await this.processGadgetsPOST(_response);
    }

    protected async processGadgetsPOST(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            const _responseText = await response.text();
            return;
        } else if (status === 401) {
            const _responseText_1 = await response.text();
            let result401: any = null;
            result401 = _responseText_1 === "" ? null : JSON.parse(_responseText_1, this.jsonParseReviver) as ProblemDetails;
            return throwException("If user is unauthorized", status, _responseText_1, _headers, result401);
        } else if (status !== 200 && status !== 204) {
            const _responseText_2 = await response.text();
            return throwException("An unexpected server error occurred.", status, _responseText_2, _headers);
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * Updates the gadget
     * @param body (optional) UpdateGadgetDto object
     * @return Success
     */
    async gadgetsPUT(body: UpdateGadgetDto | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/gadgets";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PUT",
            headers: {
                "Content-Type": "application/json-patch+json",
            }
        };

        const transformedOptions_ = await this.transformOptions(options_);
        const _response = await this.http.fetch(url_, transformedOptions_);
        return await this.processGadgetsPUT(_response);
    }

    protected async processGadgetsPUT(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 204) {
            const _responseText = await response.text();
            return;
        } else if (status === 401) {
            const _responseText_1 = await response.text();
            let result401: any = null;
            result401 = _responseText_1 === "" ? null : JSON.parse(_responseText_1, this.jsonParseReviver) as ProblemDetails;
            return throwException("If user is unauthorized", status, _responseText_1, _headers, result401);
        } else if (status !== 200 && status !== 204) {
            const _responseText_2 = await response.text();
            return throwException("An unexpected server error occurred.", status, _responseText_2, _headers);
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * Get the gadget by id
     * @param id Gadget id (guid)
     * @return Success
     */
    async gadgetsGET2(id: number): Promise<GadgetsDetailsVm> {
        let url_ = this.baseUrl + "/api/gadgets/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        const transformedOptions_ = await this.transformOptions(options_);
        const _response = await this.http.fetch(url_, transformedOptions_);
        return await this.processGadgetsGET2(_response);
    }

    protected async processGadgetsGET2(response: Response): Promise<GadgetsDetailsVm> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            const _responseText = await response.text();
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as GadgetsDetailsVm;
            return result200;
        } else if (status === 401) {
            const _responseText_1 = await response.text();
            let result401: any = null;
            result401 = _responseText_1 === "" ? null : JSON.parse(_responseText_1, this.jsonParseReviver) as ProblemDetails;
            return throwException("If user is unauthorized", status, _responseText_1, _headers, result401);
        } else if (status !== 200 && status !== 204) {
            const _responseText_2 = await response.text();
            return throwException("An unexpected server error occurred.", status, _responseText_2, _headers);
        }
        return Promise.resolve<GadgetsDetailsVm>(null as any);
    }

    /**
     * Delete the gadget by id
     * @param id Id of the gadget (guid)
     * @return Success
     */
    async gadgetsDELETE(id: number): Promise<void> {
        let url_ = this.baseUrl + "/api/gadgets/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            headers: {
            }
        };

        const transformedOptions_ = await this.transformOptions(options_);
        const _response = await this.http.fetch(url_, transformedOptions_);
        return await this.processGadgetsDELETE(_response);
    }

    protected async processGadgetsDELETE(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 204) {
            const _responseText = await response.text();
            return;
        } else if (status === 401) {
            const _responseText_1 = await response.text();
            let result401: any = null;
            result401 = _responseText_1 === "" ? null : JSON.parse(_responseText_1, this.jsonParseReviver) as ProblemDetails;
            return throwException("If user is unauthorized", status, _responseText_1, _headers, result401);
        } else if (status !== 200 && status !== 204) {
            const _responseText_2 = await response.text();
            return throwException("An unexpected server error occurred.", status, _responseText_2, _headers);
        }
        return Promise.resolve<void>(null as any);
    }
}

export interface CreateGadgetDto {
    gadgetId?: number;
    title: string;
    details?: string | undefined;
}

export interface GadgetListVm {
    gadgets?: GadgetLookupDto[] | undefined;
}

export interface GadgetLookupDto {
    id?: string;
    title?: string | undefined;
}

export interface ProblemDetails {
    type?: string | undefined;
    title?: string | undefined;
    status?: number | undefined;
    detail?: string | undefined;
    instance?: string | undefined;
}

export interface UpdateGadgetDto {
    id?: string;
    gadgetId?: number;
    title?: string | undefined;
    details?: string | undefined;
}

export interface GadgetsDetailsVm {
    id?: string;
    title?: string | undefined;
    details?: string | undefined;
    creationDate?: Date;
    editDate?: Date | undefined;
}

export class ApiException extends Error {
    message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}